vars: {
  d2-config: {
    dark-theme-id: 200
    sketch: true
    layout-engine: elk
  }
}

direction: down

linkding: "linkding" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/linkding.svg
}

homepage: "homepage" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png
}

mealie: "mealie" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/mealie.svg
}

nginx: "nginx" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nginx.svg
}

cert-manager: "cert-manager" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cert-manager.svg
}

cloudflare: "cloudflare" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cloudflare.svg
}

cnpg: "cnpg" {
  shape: image
  icon: https://cloudnative-pg.io/images/hero_image.svg
}

eso: "eso" {
  shape: image
  icon: https://external-secrets.io/latest/pictures/eso-round-logo.svg
}

vault: "vault" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/hashicorp-vault.svg
}

prometheus: "prometheus" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/prometheus.svg
}

grafana: "grafana" {
  shape: image
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg
}

k3s: "k3s" {
  shape: image
  icon: https://raw.githubusercontent.com/cncf/artwork/refs/heads/main/projects/k3s/icon/color/k3s-icon-color.svg
}
